name: dask-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab=3
  - numpy=1.23
  - scipy=1.8
  - bokeh=2.4
  - dask=2022.9.0
  - dask-labextension
  - distributed=2022.9.0
  - matplotlib
  - pandas=1.4
  - pip
  - python-graphviz
  - ipycytoscape
  - pyarrow
  - pooch
  - mamba
  - pip:
    - dask-awkward==2022.8a1
    - dask-histogram
